## 1. USING NLTK

In [2]:
import nltk
from nltk import word_tokenize, sent_tokenize
# nltk.download("punkt_tab")

In [5]:
text = "Hello world! NLP is amazing. Let's tokenize this sentence."

# Word Tokenization
print("word tokens:", word_tokenize(text))

# Sentence Tokenization
print("Sentence Tokens:", sent_tokenize(text))

word tokens: ['Hello', 'world', '!', 'NLP', 'is', 'amazing', '.', 'Let', "'s", 'tokenize', 'this', 'sentence', '.']
Sentence Tokens: ['Hello world!', 'NLP is amazing.', "Let's tokenize this sentence."]


## 2. USING SpaCy

In [6]:
import spacy
nlp = spacy.load("en_core_web_sm")

doc = nlp(text)
print("Word tokens:", [token.text for token in doc])
print("Sentence tokens:", [sent.text for sent in doc.sents])

Word tokens: ['Hello', 'world', '!', 'NLP', 'is', 'amazing', '.', 'Let', "'s", 'tokenize', 'this', 'sentence', '.']
Sentence tokens: ['Hello world!', 'NLP is amazing.', "Let's tokenize this sentence."]


# NLP Tasks

### Basic Word Count & Frequency Distribution

In [9]:
from collections import Counter
words = word_tokenize(text.lower())
word_freq = Counter(words)
print("Total Word Count:", len(words))
print("Word Frequency Distribution:", word_freq.most_common(5))
print(word_freq)

Total Word Count: 13
Word Frequency Distribution: [('.', 2), ('hello', 1), ('world', 1), ('!', 1), ('nlp', 1)]
Counter({'.': 2, 'hello': 1, 'world': 1, '!': 1, 'nlp': 1, 'is': 1, 'amazing': 1, 'let': 1, "'s": 1, 'tokenize': 1, 'this': 1, 'sentence': 1})


### Stopwords removal with frequency analysis

In [11]:
from nltk.corpus import stopwords
# nltk.downlaod("stopwords")

stop_words = set(stopwords.words("english"))
filtered_words = [word for word in words if word not in stop_words]
filtered_freq = Counter(filtered_words)

print(filtered_words)
print("Filtered Word Frequency Distribution:", filtered_freq.most_common(5))

['hello', 'world', '!', 'nlp', 'amazing', '.', 'let', "'s", 'tokenize', 'sentence', '.']
Filtered Word Frequency Distribution: [('.', 2), ('hello', 1), ('world', 1), ('!', 1), ('nlp', 1)]


### NER with Context Analysis

In [15]:
import spacy
from collections import Counter

nlp = spacy.load("en_core_web_sm")
text = "Apple is looking at buying U.K. startup for $1 billion."
doc = nlp(text)

entities = [ent.text for ent in doc.ents]
entity_freq = Counter(entities)

for ent, freq in entity_freq.most_common():
    print(f"Entity:{ent}, Count : {freq}, Label : {nlp(ent)[0].ent_type_}")

Entity:Apple, Count : 1, Label : ORG
Entity:U.K., Count : 1, Label : GPE
Entity:$1 billion, Count : 1, Label : MONEY


### N-Grams with frequency analysis

In [22]:
from nltk.util import ngrams
bigrams = list(ngrams(words, 2))
trigrams = list(ngrams(words, 3))

bigrams_freq = Counter(bigrams)
trigrams_freq = Counter(trigrams)

print("Most Common Bigrams:", bigrams_freq.most_common(5))
print("Most Common Trigrams:", trigrams_freq.most_common(5))

Most Common Bigrams: [(('hello', 'world'), 1), (('world', '!'), 1), (('!', 'nlp'), 1), (('nlp', 'is'), 1), (('is', 'amazing'), 1)]
Most Common Trigrams: [(('hello', 'world', '!'), 1), (('world', '!', 'nlp'), 1), (('!', 'nlp', 'is'), 1), (('nlp', 'is', 'amazing'), 1), (('is', 'amazing', '.'), 1)]


### Keyword Extraction using TF-IDF with Tokenization

In [38]:
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()

X = tfidf.fit_transform([text])

feature_array = np.array(tfidf.get_feature_names_out())

importance = np.argsort(X.toarray()).flatten()[::-1]

keywords = feature_array[importance[:5]]
print("Top Keywords:", keywords)


Top Keywords: ['startup' 'looking' 'is' 'for' 'buying']


### POS Tagging

In [43]:
doc = nlp(text)

for token in doc:
    print(
        f"Token: {token.text}, "
        f"POS: {token.pos_}, "
        f"Def.: {spacy.explain(token.pos_)}"
    )

Token: Apple, POS: PROPN, Def.: proper noun
Token: is, POS: AUX, Def.: auxiliary
Token: looking, POS: VERB, Def.: verb
Token: at, POS: ADP, Def.: adposition
Token: buying, POS: VERB, Def.: verb
Token: U.K., POS: PROPN, Def.: proper noun
Token: startup, POS: VERB, Def.: verb
Token: for, POS: ADP, Def.: adposition
Token: $, POS: SYM, Def.: symbol
Token: 1, POS: NUM, Def.: numeral
Token: billion, POS: NUM, Def.: numeral
Token: ., POS: PUNCT, Def.: punctuation


### Sentence Similarity

In [47]:
from sklearn.feature_extraction.text import CountVectorizer

sentences = ["I love NLP", "NLP is great for text processing", "Machine learning is amazing"]

cv = CountVectorizer()

X = cv.fit_transform(sentences)

print(X.toarray())
print(cv.vocabulary_)
print(cv.get_feature_names_out())

print("Sentence Similarity Matrix:")
print((X * X.T).toarray())

[[0 0 0 0 0 1 0 1 0 0]
 [0 1 1 1 0 0 0 1 1 1]
 [1 0 0 1 1 0 1 0 0 0]]
{'love': 5, 'nlp': 7, 'is': 3, 'great': 2, 'for': 1, 'text': 9, 'processing': 8, 'machine': 6, 'learning': 4, 'amazing': 0}
['amazing' 'for' 'great' 'is' 'learning' 'love' 'machine' 'nlp'
 'processing' 'text']
Sentence Similarity Matrix:
[[2 1 0]
 [1 6 1]
 [0 1 4]]


### Text Summarization

In [51]:
import spacy
import nltk
from nltk import word_tokenize
from collections import Counter

# download required NLTK tokenizer
# nltk.download("punkt")

#load SpaCy model
nlp = spacy.load("en_core_web_sm")

# Input text
text = """Natural Language Processing (NLP) is a field of AI that enables machines to understand human language.
It is used in chatbots, sentiment analysis, and language translation.
One of the key challenges in NLP is understanding context and ambiguity in sentences.
Deep learning models like transformers have significantly improved NLP applications."""

# process text with spaCy
doc = nlp(text)

#Tokenize words and compute frequency
words = [word.lower() for word in word_tokenize(text) if word.isalnum()]
filtered_freq = Counter(words)

#compute sentece scores
sentence_scores = {}

for sent in doc.sents:
    for word in word_tokenize(sent.text.lower()):
        if word in filtered_freq:
            sentence_scores[sent.text] = sentence_scores.get(sent.text, 0) + filtered_freq[word]
    
# Sort sentences by score
sorted_sentences = sorted(sentence_scores, key = sentence_scores.get, reverse = True)

# select top-ranked sentences for summary
summary = " ".join(sorted_sentences[:2])

#summary
print("Summary:", summary)



Summary: Natural Language Processing (NLP) is a field of AI that enables machines to understand human language.
 One of the key challenges in NLP is understanding context and ambiguity in sentences.

