# Text - classification using ML

## Data Acquisition

In [ ]:
!pip install kagglehub

In [5]:
import kagglehub

# Download dataset
path = kagglehub.dataset_download(
    "lakshmi25npathi/imdb-dataset-of-50k-movie-reviews"
)

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'imdb-dataset-of-50k-movie-reviews' dataset.
Path to dataset files: /kaggle/input/imdb-dataset-of-50k-movie-reviews


In [6]:
import os

print(os.listdir(path))

['IMDB Dataset.csv']


In [7]:
import pandas as pd
import os

csv_path = os.path.join(path, "IMDB Dataset.csv")

df = pd.read_csv(csv_path)

df.head()

,review,sentiment
0,One of the other reviewers has mentioned that ...,positive
1,A wonderful little production. <br /><br />The...,positive
2,I thought this was a wonderful way to spend ti...,positive
3,Basically there's a family where a little boy ...,negative
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive


## EDA

In [ ]:
df['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fa

In [ ]:
df['sentiment'].value_counts()

,count
sentiment,
positive,25000
negative,25000


In [ ]:
df.isnull().sum()

,0
review,0
sentiment,0


In [ ]:
df.duplicated().sum()

np.int64(418)

In [ ]:
df.drop_duplicates(inplace = True)

In [ ]:
df.duplicated().sum()

np.int64(0)

## Text Preprocessing

### 1. Lowercasing

In [ ]:
df['review'] = df['review'].str.lower()

In [ ]:
df.head()

,review,sentiment
0,one of the other reviewers has mentioned that ...,positive
1,a wonderful little production. <br /><br />the...,positive
2,i thought this was a wonderful way to spend ti...,positive
3,basically there's a family where a little boy ...,negative
4,"petter mattei's ""love in the time of money"" is...",positive


### 2. Removing HTML tags

In [ ]:
df.review[0]

"one of the other reviewers has mentioned that after watching just 1 oz episode you'll be hooked. they are right, as this is exactly what happened with me.<br /><br />the first thing that struck me about oz was its brutality and unflinching scenes of violence, which set in right from the word go. trust me, this is not a show for the faint hearted or timid. this show pulls no punches with regards to drugs, sex or violence. its is hardcore, in the classic use of the word.<br /><br />it is called oz as that is the nickname given to the oswald maximum security state penitentary. it focuses mainly on emerald city, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. em city is home to many..aryans, muslims, gangstas, latinos, christians, italians, irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />i would say the main appeal of the show is due to the fa

In [ ]:
import re
def remove_tags(text):
  pattern = r'<.*?>'
  return re.sub(pattern, "", text);

In [ ]:
df['review'] = df['review'].apply(remove_tags)

In [ ]:
df["review"][0]

"one of the other reviewers has mentioned that after watching just 1 oz episode you'll be hooked. they are right, as this is exactly what happened with me.the first thing that struck me about oz was its brutality and unflinching scenes of violence, which set in right from the word go. trust me, this is not a show for the faint hearted or timid. this show pulls no punches with regards to drugs, sex or violence. its is hardcore, in the classic use of the word.it is called oz as that is the nickname given to the oswald maximum security state penitentary. it focuses mainly on emerald city, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. em city is home to many..aryans, muslims, gangstas, latinos, christians, italians, irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.i would say the main appeal of the show is due to the fact that it goes where other shows wo

### 3. Removing URLs

In [ ]:
import re

def remove_urls(text):
    pattern = r'https?://\S+|www\.\S+'
    text = re.sub(pattern, '', text)
    print(re.findall(pattern, text))
    return re.sub(r'\s+', ' ', text).strip()

In [ ]:
df['review'] = df['review'].apply(remove_urls)

Streaming output truncated to the last 5000 lines.
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[

### 4. Remove Punctuations

In [ ]:
df.head()

,review,sentiment
0,one of the other reviewers has mentioned that ...,positive
1,a wonderful little production. the filming tec...,positive
2,i thought this was a wonderful way to spend ti...,positive
3,basically there's a family where a little boy ...,negative
4,"petter mattei's ""love in the time of money"" is...",positive


In [ ]:
import string
exclude = string.punctuation

In [ ]:
def remove_punctuations(text):
  return text.translate(str.maketrans('', '', exclude))

In [ ]:
import time
start = time.time()
df['review'] = df['review'].apply(remove_punctuations)
end = time.time()
print(end - start)

1.8241798877716064


In [ ]:
df.head()

,review,sentiment
0,one of the other reviewers has mentioned that ...,positive
1,a wonderful little production the filming tech...,positive
2,i thought this was a wonderful way to spend ti...,positive
3,basically theres a family where a little boy j...,negative
4,petter matteis love in the time of money is a ...,positive


### 5. Chat conversation

### 6. Spelling correction

In [ ]:
from textblob import TextBlob

In [ ]:
def correct_spelling(text):
  return TextBlob(text).correct().string

In [ ]:
correct_spelling("ceertain conditionas duriiing several ggennerations aree modifiedss in the saame manerr.")

'certain conditions during several generations are modified in the same manner.'

In [ ]:
# df['review'] = df['review'].apply(correct_spelling)

### 7. Removing Stop Words

In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))

def remove_stopwords(text):
    filtered_words = [
        word for word in text.split()
        if word.lower() not in stop_words
    ]
    return ' '.join(filtered_words)

In [ ]:
df['review'] = df['review'].apply(remove_stopwords)

### 8. Demojize

In [ ]:
!pip install emoji

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 608.4/608.4 kB 11.0 MB/s eta 0:00:00


In [ ]:
import emoji

In [ ]:
def text_demojize(text):
  return emoji.demojize(text)

In [ ]:
df['review'] = df['review'].apply(text_demojize)

### 9. Stemming

In [ ]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [ ]:
def stem_words(text):
  return " ".join(ps.stem(word) for word in text.split())

In [ ]:
df['review'] = df['review'].apply(stem_words)

**I will do this part next day so i stored this cleaned df**

In [2]:
import pandas as pd
import numpy as np


import warnings
warnings.filterwarnings("ignore")

In [3]:
save_path = "/content/drive/MyDrive/NLP/Text-classification/cleaned_imdb.csv"

# df.to_csv(save_path, index=False)

# print("File saved successfully")

In [4]:
df = pd.read_csv(save_path)

In [5]:
df.head()

,review,sentiment
0,one review mention watch 1 oz episod youll hoo...,positive
1,wonder littl product film techniqu unassum old...,positive
2,thought wonder way spend time hot summer weeke...,positive
3,basic there famili littl boy jake think there ...,negative
4,petter mattei love time money visual stun film...,positive


# Modelling - ML approach

## 1. with BOW

In [6]:
X = df.drop('sentiment', axis = 1)
y = df['sentiment']

In [7]:
X.shape, y.shape

((49582, 1), (49582,))

In [8]:
X.head()

,review
0,one review mention watch 1 oz episod youll hoo...
1,wonder littl product film techniqu unassum old...
2,thought wonder way spend time hot summer weeke...
3,basic there famili littl boy jake think there ...
4,petter mattei love time money visual stun film...


In [9]:
y.head()

,sentiment
0,positive
1,positive
2,positive
3,negative
4,positive


In [10]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

y = encoder.fit_transform(y)

In [11]:
y

array([1, 1, 1, ..., 0, 0, 0])

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test , y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 2)


In [14]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((39665, 1), (9917, 1), (39665,), (9917,))

In [39]:
# applying BOW
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 5000) # if we take frequent 5k words accuracy is good if we increase it decreases

In [40]:
X_train_bow = cv.fit_transform(X_train['review']).toarray()

In [41]:
X_train_bow.shape

(39665, 5000)

In [42]:
X_test_bow = cv.transform(X_test['review']).toarray()

In [43]:
X_test_bow.shape

(9917, 5000)

In [44]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

In [45]:
gnb.fit(X_train_bow, y_train)

GaussianNB()

In [46]:
y_pred = gnb.predict(X_test_bow)

In [47]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [48]:
accuracy_score(y_test, y_pred)

0.7245134617323787

In [49]:
confusion_matrix(y_test, y_pred)

array([[4229,  705],
       [2027, 2956]])

In [50]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()

rf.fit(X_train_bow, y_train)

RandomForestClassifier()

In [51]:
y_pred = rf.predict(X_test_bow)
accuracy_score(y_test, y_pred)

0.8430977110013109

In [52]:
confusion_matrix(y_test, y_pred)

array([[4124,  810],
       [ 746, 4237]])

## 2. using ngrams

In [53]:
# applying ngrams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range = (2,2), max_features = 5000)

X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.transform(X_test['review']).toarray()

from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

gnb.fit(X_train_bow, y_train)

y_pred = gnb.predict(X_test_bow)

print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

0.7897549662196228
[[3643 1291]
 [ 794 4189]]


In [54]:
# applying ngrams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range = (1,2), max_features = 5000)

X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.transform(X_test['review']).toarray()

from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

gnb.fit(X_train_bow, y_train)

y_pred = gnb.predict(X_test_bow)

print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

0.8060905515780982
[[4249  685]
 [1238 3745]]


## 3. Using TfIdf

In [55]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_features = 5000)

X_train_tfidf = tfidf.fit_transform(X_train['review']).toarray()
X_test_tfidf = tfidf.transform(X_test['review']).toarray()


In [56]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

gnb.fit(X_train_bow, y_train)

y_pred = gnb.predict(X_test_bow)

print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

0.8060905515780982
[[4249  685]
 [1238 3745]]


## 4. Word2Vec

- pretrained model (80% vocab should be matched)
- self-trained word2vec