## **Tensors**

- Tensor is a specialized multi-dimensional array designed for mathematical and computational efficiency.

---

## **Real-World Examples**

### **1. Scalars (0-Dimensional Tensors)**
- A single number.
- Example:
  - Loss value after the forward pass.
  - `5.0`, `-4.5`

---

### **2. Vectors (1-Dimensional Tensors)**
- Represents a sequence or collection of values.
- Example:
  - Feature vector in NLP (word embeddings).
  - `[0.12, -0.34, 0.33]`

---

### **3. Matrices (2-Dimensional Tensors)**
- Represents tabular or grid-like data.
- Example:
  - Grayscale image represented as a 2D tensor.

---

### **4. 3D Tensors**
- Adds a third dimension, often used for stacking data.
- Example:
  - RGB (Colored) images.

---

### **5. 4D Tensors**
- Adds the batch size as an additional dimension to 3D data.
- Example:
  - Batch of RGB images.
  - Shape: `[batch_size, width, height, channels]`

---

### **6. 5D Tensors**
- Adds a time dimension for data that changes over time.
- Example:
  - Video data (sequence of RGB frames).
  - Shape: `[batch_size, frames, width, height, channels]`
  - Example Shape: `[10, 16, 64, 64, 3]`
    - `10` → Video clips (batch size)
    - `16` → Frames per video
    - `64 × 64` → Frame resolution
    - `3` → RGB channels

## **Why are Tensors Useful?**

### **1. Mathematical Computations**
- Tensors enable efficient mathematical computations such as:
  - Addition
  - Multiplication
  - Dot Product
- These operations are essential for neural network computations.

---

### **2. Representation of Real-World Data**
- Real-world data such as images, audio, and text can be represented as tensors.

#### Examples:
- **Images:** Represented as 3D tensors `(Width × Height × Channels)`
- **Text:** Tokenized and represented as 2D or 3D tensors

---

### **3. Efficient Computations**
- Tensors are optimized for hardware acceleration.
- They can be processed efficiently on:
  - GPUs (Graphics Processing Units)
  - TPUs (Tensor Processing Units)
- This makes training deep learning models significantly faster.

---

## **Where are Tensors Used in Deep Learning?**

### **1. Data Storage**
- Training data such as:
  - Images
  - Text
  - Audio
- is stored in the form of tensors.

---

### **2. Weights and Biases**
- The learnable parameters of neural networks are stored as tensors.
- Examples:
  - Weight matrices
  - Bias vectors

---

### **3. Matrix Operations**
- Neural networks heavily rely on tensor operations such as:
  - Matrix Multiplication
  - Dot Products
  - Broadcasting
- All these operations are performed using tensors.

---

### **4. Training Process**

#### **Forward Pass**
- Tensors flow through the network layer by layer.
- Computations are performed to generate predictions.

#### **Backward Pass**
- Gradients are computed during backpropagation.
- These gradients are also represented as tensors and are used to update model parameters.

In [1]:
import torch
print(torch.__version__)

2.11.0+cu128


In [2]:
print("CUDA Available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU Name:", torch.cuda.get_device_name(0))
    print("Number of GPUs:", torch.cuda.device_count())
else:
    print("No GPU detected.")

CUDA Available: True
GPU Name: Tesla T4
Number of GPUs: 1


# Creating a Tensor

In [7]:
# using empty
a = torch.empty(2, 3) # memory allication of 2x3 with garbage values
print(a)
print(type(a))

tensor([[0.0000e+00, 1.6255e-43, 7.7052e+31],
        [1.9447e+31, 2.1715e-18, 2.3081e-12]])
<class 'torch.Tensor'>


In [8]:
torch.zeros(2, 3) # memory allication of 2x3 with zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
torch.ones(2, 3) # memory allication of 2x3 with ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
torch.rand(2, 3) # memory allication of 2x3 with random

tensor([[0.3913, 0.8795, 0.2751],
        [0.6771, 0.6403, 0.5490]])

In [11]:
torch.manual_seed(93)
torch.rand(2, 3) # memory allication of 2x3 with random

tensor([[0.2267, 0.3016, 0.3230],
        [0.6414, 0.6537, 0.9653]])

In [12]:
torch.rand(2, 3)

tensor([[0.2729, 0.8871, 0.1952],
        [0.3677, 0.8665, 0.3214]])

In [13]:
# using tensor
torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [17]:
#arange
print("using arange ->", torch.arange(0, 10, 2))

# using linspace
print("using linspace ->", torch.linspace(0, 10, 5)) # evenly spaced values

# using eye
print("using eye ->", torch.eye(5))

#using full
print("using full ->", torch.full((2, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5]])


## Tensor shapes

In [21]:
print("tensor is: ", a)
print("shape of a tensor is: ", a.shape)

tensor is:  tensor([[0.0000e+00, 1.6255e-43, 7.7052e+31],
        [1.9447e+31, 2.1715e-18, 2.3081e-12]])
shape of a tensor is:  torch.Size([2, 3])


In [23]:
a.shape[0], a.shape[1]

(2, 3)

In [24]:
torch.empty_like(a) # values different but shape will be same

tensor([[-1.8210e+24,  4.3334e-41,  1.2427e-15],
        [ 0.0000e+00,  2.0022e-19,  7.7452e+31]])

In [25]:
torch.zeros_like(a)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [26]:
torch.ones_like(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [27]:
torch.rand_like(a)

tensor([[0.8404, 0.4876, 0.2519],
        [0.9633, 0.8617, 0.4417]])

## Tensor Data Types

In [29]:
# find data type
a.dtype

torch.float32

In [31]:
t1 =  torch.tensor([[1, 2, 3],[4, 5, 6]])
print(t1)
print(t1.shape)
print(t1.dtype)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
torch.int64


In [32]:
t2 = t1.to(torch.float32)
print(t2)
print(t2.shape)
print(t2.dtype)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])
torch.float32


In [34]:
# torch.rand_like(t1) #--> it will give error since t1 is int and rand assume float

In [35]:
torch.rand_like(t1, dtype = torch.float32)

tensor([[0.8494, 0.1409, 0.3131],
        [0.2812, 0.5857, 0.7136]])

# mathematical operations

1. Scaler operations

In [37]:
t2

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [38]:
print(t2 + 2)
print(t2 - 2)
print(t2 * 2)
print(t2 / 2)
print(t2 // 2)
print(t2 % 2)

tensor([[3., 4., 5.],
        [6., 7., 8.]])
tensor([[-1.,  0.,  1.],
        [ 2.,  3.,  4.]])
tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])
tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000]])
tensor([[0., 1., 1.],
        [2., 2., 3.]])
tensor([[1., 0., 1.],
        [0., 1., 0.]])


In [39]:
torch.abs(t2-2)

tensor([[1., 0., 1.],
        [2., 3., 4.]])

In [41]:
torch.round(t2/2)

tensor([[0., 1., 2.],
        [2., 2., 3.]])

In [42]:
torch.floor(t2/2)

tensor([[0., 1., 1.],
        [2., 2., 3.]])

In [43]:
torch.ceil(t2/2)

tensor([[1., 1., 2.],
        [2., 3., 3.]])

In [44]:
torch.clamp(t2*2, min = 2, max = 3)

tensor([[2., 3., 3.],
        [3., 3., 3.]])

# 2. element wise operations

In [46]:
A = torch.rand(3, 3)
B = torch.rand(3, 3)

print("Tensor A:\n", A)
print("\nTensor B:\n", B)


print("\nElement-wise Addition (A + B):")
print(A + B)

print("\nElement-wise Subtraction (A - B):")
print(A - B)

print("\nElement-wise Multiplication (A * B):")
print(A * B)

print("\nElement-wise Division (A / B):")
print(A / B)

print("\nElement-wise Power (A ** 2):")
print(A ** 2)


print("\nA > B:")
print(A > B)

print("\nA == B:")
print(A == B)


print("\nSquare Root of A:")
print(torch.sqrt(A))

print("\nExponential of A:")
print(torch.exp(A))

print("\nNatural Log of A:")
print(torch.log(A))


Tensor A:
 tensor([[0.4773, 0.3457, 0.6805],
        [0.0336, 0.7657, 0.6774],
        [0.4435, 0.6704, 0.0552]])

Tensor B:
 tensor([[0.4004, 0.3505, 0.2602],
        [0.6890, 0.7207, 0.5499],
        [0.2654, 0.0544, 0.2798]])

Element-wise Addition (A + B):
tensor([[0.8777, 0.6962, 0.9407],
        [0.7227, 1.4864, 1.2273],
        [0.7089, 0.7247, 0.3350]])

Element-wise Subtraction (A - B):
tensor([[ 0.0769, -0.0048,  0.4203],
        [-0.6554,  0.0450,  0.1275],
        [ 0.1781,  0.6160, -0.2245]])

Element-wise Multiplication (A * B):
tensor([[0.1911, 0.1212, 0.1771],
        [0.0232, 0.5519, 0.3725],
        [0.1177, 0.0365, 0.0155]])

Element-wise Division (A / B):
tensor([[ 1.1922,  0.9864,  2.6154],
        [ 0.0488,  1.0625,  1.2319],
        [ 1.6708, 12.3288,  0.1975]])

Element-wise Power (A ** 2):
tensor([[0.2278, 0.1195, 0.4631],
        [0.0011, 0.5863, 0.4589],
        [0.1967, 0.4494, 0.0031]])

A > B:
tensor([[ True, False,  True],
        [False,  True,  True],
 

## 3. Reduction operation

In [49]:

print("\nSum of all elements in A:")
print(torch.sum(A))

print("\nMean of A:")
print(torch.mean(A))

print("\nMaximum value in A:")
print(torch.max(A))

print("\nMinimum value in A:")
print(torch.min(A))

print(torch.median(A))

print(torch.prod(A))

print(torch.std(A))

print(torch.argmax(A))

print(torch.argmin(A))


Sum of all elements in A:
tensor(4.1494)

Mean of A:
tensor(0.4610)

Maximum value in A:
tensor(0.7657)

Minimum value in A:
tensor(0.0336)
tensor(0.4773)
tensor(3.2192e-05)
tensor(0.2722)
tensor(4)
tensor(3)


In [50]:
torch.matmul(A, B)

tensor([[0.6099, 0.4534, 0.5047],
        [0.7209, 0.6005, 0.6194],
        [0.6541, 0.6416, 0.4995]])

In [54]:
torch.transpose(A, 0, 1)

tensor([[0.4773, 0.0336, 0.4435],
        [0.3457, 0.7657, 0.6704],
        [0.6805, 0.6774, 0.0552]])

In [56]:
torch.det(A)

tensor(-0.3091)

In [57]:
torch.inverse(A)

tensor([[ 1.3323, -1.4141,  0.9282],
        [-0.9659,  0.8911,  0.9720],
        [ 1.0256,  0.5392, -1.1448]])

## 5. Comparision functions

In [58]:
A = torch.randint(1, 10, (3, 3))
B = torch.randint(1, 10, (3, 3))

print("A:\n", A)
print("\nB:\n", B)

# Comparison operations

print("\nA == B")
print(A == B)

print("\nA != B")
print(A != B)

print("\nA > B")
print(A > B)

print("\nA < B")
print(A < B)

print("\nA >= B")
print(A >= B)

print("\nA <= B")
print(A <= B)

A:
 tensor([[6, 8, 3],
        [7, 9, 8],
        [5, 1, 8]])

B:
 tensor([[3, 2, 3],
        [7, 1, 5],
        [8, 8, 2]])

A == B
tensor([[False, False,  True],
        [ True, False, False],
        [False, False, False]])

A != B
tensor([[ True,  True, False],
        [False,  True,  True],
        [ True,  True,  True]])

A > B
tensor([[ True,  True, False],
        [False,  True,  True],
        [False, False,  True]])

A < B
tensor([[False, False, False],
        [False, False, False],
        [ True,  True, False]])

A >= B
tensor([[ True,  True,  True],
        [ True,  True,  True],
        [False, False,  True]])

A <= B
tensor([[False, False,  True],
        [ True, False, False],
        [ True,  True, False]])


## 5. Special functions

In [59]:
torch.log(A)

tensor([[1.7918, 2.0794, 1.0986],
        [1.9459, 2.1972, 2.0794],
        [1.6094, 0.0000, 2.0794]])

In [60]:
torch.exp(A)

tensor([[4.0343e+02, 2.9810e+03, 2.0086e+01],
        [1.0966e+03, 8.1031e+03, 2.9810e+03],
        [1.4841e+02, 2.7183e+00, 2.9810e+03]])

In [61]:
torch.sqrt(A)

tensor([[2.4495, 2.8284, 1.7321],
        [2.6458, 3.0000, 2.8284],
        [2.2361, 1.0000, 2.8284]])

In [62]:
torch.sigmoid(A)

tensor([[0.9975, 0.9997, 0.9526],
        [0.9991, 0.9999, 0.9997],
        [0.9933, 0.7311, 0.9997]])

In [69]:
A = A.to(torch.float32)
torch.softmax(A, dim = 1)

tensor([[1.1850e-01, 8.7560e-01, 5.8998e-03],
        [9.0031e-02, 6.6524e-01, 2.4473e-01],
        [4.7385e-02, 8.6788e-04, 9.5175e-01]])

In [70]:
torch.relu(A)

tensor([[6., 8., 3.],
        [7., 9., 8.],
        [5., 1., 8.]])

## Inplace operations

In [71]:
import torch

A = torch.tensor([1, 2, 3], dtype=torch.float32)

print("Original:", A)

# In-place addition
A.add_(5)
print("\nAfter add_:", A)

# In-place subtraction
A.sub_(2)
print("\nAfter sub_:", A)

# In-place multiplication
A.mul_(3)
print("\nAfter mul_:", A)

# In-place division
A.div_(2)
print("\nAfter div_:", A)

# In-place power
A.pow_(2)
print("\nAfter pow_:", A)

Original: tensor([1., 2., 3.])

After add_: tensor([6., 7., 8.])

After sub_: tensor([4., 5., 6.])

After mul_: tensor([12., 15., 18.])

After div_: tensor([6.0000, 7.5000, 9.0000])

After pow_: tensor([36.0000, 56.2500, 81.0000])


## Copying a tensor

In [74]:
A = torch.tensor([1, 2, 3])

B = A

B[0] = 100

print("A:", A)
print("B:", B)

# here A is changed , beccause of same id
print(id(A))
print(id(B))

A: tensor([100,   2,   3])
B: tensor([100,   2,   3])
132815551778240
132815551778240


In [72]:

# Copy tensor
B = A.clone()

B[0] = 100

print("A:", A)
print("B:", B)

A: tensor([1, 2, 3])
B: tensor([100,   2,   3])


# Tensor Operations on GPU

In [75]:
torch.cuda.is_available()

True

In [76]:
device = torch.device('cuda')

In [77]:
# creating a new tensor on GPU
torch.rand((2, 3), device = device)

tensor([[0.6454, 0.7936, 0.1890],
        [0.8165, 0.1804, 0.4045]], device='cuda:0')

In [79]:
# moving an existing tensor to GPU
a = torch.rand(2, 3)
b = a.to(device)

In [80]:
b + 5

tensor([[5.2221, 5.4651, 5.3384],
        [5.9728, 5.6535, 5.3127]], device='cuda:0')

## comparision between cpu and gpu tensors

In [81]:
import torch
import time

size = 5000

# CPU benchmark
A_cpu = torch.rand(size, size)
B_cpu = torch.rand(size, size)

start = time.time()
C_cpu = A_cpu @ B_cpu
cpu_time = time.time() - start

print(f"CPU Time: {cpu_time:.4f} seconds")

# GPU benchmark
if torch.cuda.is_available():

    A_gpu = A_cpu.to("cuda")
    B_gpu = B_cpu.to("cuda")

    torch.cuda.synchronize()
    start = time.time()

    C_gpu = A_gpu @ B_gpu

    torch.cuda.synchronize()
    gpu_time = time.time() - start

    print(f"GPU Time: {gpu_time:.4f} seconds")
    print(f"Speedup: {cpu_time / gpu_time:.2f}x")

else:
    print("CUDA is not available")

CPU Time: 2.0151 seconds
GPU Time: 0.2138 seconds
Speedup: 9.43x


# Reshaping tensors

In [82]:
a = torch.ones(4, 4)

In [83]:
print(a)
print(torch.prod(a))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor(1.)


In [84]:
a.reshape(2, 8)

tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

In [85]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [90]:
# permute
b = torch.rand(2, 3)
print(b.shape)
b.permute(1, 0).shape

torch.Size([2, 3])


torch.Size([3, 2])

In [95]:
# unsqueeze
c = torch.rand(226, 226, 3) # image size
c.unsqueeze(0).shape # batch size

torch.Size([1, 226, 226, 3])

In [98]:
# squeeze
d = torch.rand(1, 20)
print(d.shape)
d.squeeze(0).shape

torch.Size([1, 20])


torch.Size([20])

# Numpy and PyTorch

In [99]:
import numpy as np


In [100]:
t = torch.tensor([1, 2, 3])

In [102]:
arr = t.numpy()

In [104]:
arr

array([1, 2, 3])

In [105]:
torch.from_numpy(arr)

tensor([1, 2, 3])